package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"
	"log"
	"math/rand"

	"github.com/ghsable/graphql-playground.go/graph/model"
)

// createTodo mutation
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	todo := &model.Todo{
		Text: input.Text,
		ID:   fmt.Sprintf("T%d", rand.Int()),
		//User: &model.User{ID: input.UserID, Name: "user " + input.UserID},
	}
	r.todos = append(r.todos, todo)
	return todo, nil
}

// InsertUser is the resolver for the insertUser field.
func (r *mutationResolver) InsertUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	db := ConnectDB()
	user := &model.User{
		Name:     input.Name,
		Email:    input.Email,
		IsActive: input.IsActive,
	}
	if result := db.Create(user); result.Error != nil {
		log.Fatal(result.Error)
	} else {
		fmt.Println("inserted:", result.RowsAffected)
	}
	return user, nil
}

// todos query
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	return r.todos, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	//panic(fmt.Errorf("not implemented: Hello - hello"))
	return "Hello world!!", nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id *int, name *string, email *string, isActive *bool) ([]*model.User, error) {
	db := ConnectDB()
	query := db.Model(&model.User{})
	var users []*model.User
	if id != nil {
		query = query.Where("id = ?", id)
	}
	if name != nil {
		query = query.Where("name = ?", name)
	}
	if email != nil {
		query = query.Where("email = ?", email)
	}
	if isActive != nil {
		if *isActive {
			query = query.Where("is_active IS TRUE")
		} else {
			query = query.Where("is_active IS FALSE OR is_active IS NULL")
		}
	}
	if err := query.Find(&users).Error; err != nil {
		return nil, err
	}
	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
