package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"
	"fmt"
	"math/rand"

	"github.com/ghsable/graphql-playground.go/graph/model"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// createTodo mutation
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	todo := &model.Todo{
		Text: input.Text,
		ID:   fmt.Sprintf("T%d", rand.Int()),
		User: &model.User{ID: input.UserID, Name: "user " + input.UserID},
	}
	r.todos = append(r.todos, todo)
	return todo, nil
}

// todos query
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	return r.todos, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	//panic(fmt.Errorf("not implemented: Hello - hello"))
	return "Hello world!!", nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id *int, name *string, email *string, isactive *bool) ([]*model.User, error) {
	db := ConnectDB()
	var users []*model.User
	if id != nil {
		if result := db.Where("id = ?", *id).Find(&users); result.Error != nil {
			return nil, result.Error
		}
	} else {
		if result := db.Find(&users); result.Error != nil {
			return nil, result.Error
		}
	}
	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func ConnectDB() *gorm.DB {
	dsn := "dev.db"
	db, err := gorm.Open(sqlite.Open(dsn), &gorm.Config{})
	if err != nil {
		panic("failed to connect database")
	}
	return db
}
